// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGS1piDFz42e5oe5s7babmm9S3RIMiYI',
    appId: '1:554909053715:web:645c958cf4825e840620e6',
    messagingSenderId: '554909053715',
    projectId: 'test-zoluxiones',
    authDomain: 'test-zoluxiones.firebaseapp.com',
    storageBucket: 'test-zoluxiones.firebasestorage.app',
    measurementId: 'G-B32S50C17W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL5QkPnMeA7o0c5Q2292itais3iSegqag',
    appId: '1:554909053715:android:40a484f7841357d80620e6',
    messagingSenderId: '554909053715',
    projectId: 'test-zoluxiones',
    storageBucket: 'test-zoluxiones.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWbFYjhVmFGsa4q2gVmYbBQLa2BDRoC-U',
    appId: '1:554909053715:ios:c4841c0b8591b76c0620e6',
    messagingSenderId: '554909053715',
    projectId: 'test-zoluxiones',
    storageBucket: 'test-zoluxiones.firebasestorage.app',
    iosBundleId: 'com.test_zoluxiones.app',
  );
}
